[package]
name = "proxmox-apt-mirror"
version = "0.1.0"
authors = ["Fabian Gr√ºnbichler <f.gruenbichler@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
description = "Proxmox APT repository mirror"

exclude = ["debian"]

[dependencies]
anyhow = "1.0"
bzip2 = "0.4"
flate2 = "1.0.22"
hex = "0.4.3"
hyper = "0.14"
lazy_static = "1.4"
nix = "0.24"
openssl = "0.10"
regex = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sequoia-openpgp = { version = "1.7" }
ureq = { version = "2.4.0", features = ["native-certs"] }
walkdir = "2.3.1"
xz2 = "0.1"

proxmox-apt = { path = "../proxmox-apt", version = "0.8.0" }
proxmox-async = "0.4"
proxmox-router = { version = "1.1", features = [ "cli" ] }
proxmox-schema = { version = "1.1", features = [ "api-macro" ] }
proxmox-section-config = "1"
proxmox-serde = "0.1"
proxmox-sys = { version = "0.3" }
proxmox-time = { version = "1.1.3" }
