overlay = "."
crate_src_path = ".."
maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
vcs_git = "git://git.proxmox.com/git/proxmox-offline-mirror.git"
vcs_browser = "https://git.proxmox.com/?p=proxmox-offline-mirror.git"
build_depends = [
 "latexmk",
 "fonts-open-sans",
 "fonts-lato",
]

[packages.bin]
section = "admin"
description = """
This package contains the proxmox-offline-mirror tool for managing Proxmox offline APT
repositories and subscription keys.
"""
depends = ["proxmox-offline-mirror-docs", "proxmox-archive-keyring"]
